[tool.uv.workspace]
members = ["docs/notes/graph/script"]

[project]
name = "llm-sql-phc"
version = "0.1.0"
description = "GGR algorithm for optimizing LLM queries"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "networkx>=3.6.1",
    "numpy",
    "rustworkx>=0.17.1",
]
