[project]
name = "graph-matching"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "mwmatching",
    "networkx>=3.6.1",
    "rustworkx>=0.17.1",
]

[tool.uv.sources]
mwmatching = { path = "/Users/owhite/dev/all-github/maximum-weight-matching/python", editable = true }
